### ISSUE TITLE
Improve your commits

### ISSUE THREAD

**Issue by SantiagoGuerra** [Usagib/stylofw#1]
Hi @Usagib , I can see your great effort in the last commits and your project is looking great.

In this project I can not add anything because you are handling the code in an excellent way and I can understand the CSS very well.

The only thing I would recommend is to make more descriptive commits so that other developers can be guided better in a more complex version of your project.

Good luck finishing your project.

**Comment by Usagib** [comment]
Thank you very much @SantiagoGuerra  i'll keep and eye on it on improving in have more descriptive comments
