### ISSUE TITLE
Peer to peer 19-11-19

### ISSUE THREAD

**Issue by Usagib** [Usagib/stylofw#3]

**Comment by Qoosim** [comment]
Great work @Usagib, you have really put tons of commitment to this project as you have always been. Just little observation from my own side. I think it would be fine and looked more sophisticated to use a single css property that performs work of four different properties. Like font: f-weight f-size/l-hight f-family than splitting them separately. 
Good Work dude, that's who you always are.

**Comment by Usagib** [comment]
.flex {
  display: flex;
}

this class was from the project requirements but we don't use it because the whole framework is flex items
